### ISSUE TITLE
Naming conventions ?

### ISSUE THREAD

**Issue by Oloompa** [MansaGroup/kanedama#283]
Hello, i don't find naming rules. Do you have something for that ?

**Comment by RemyTinco** [comment]
Hello @Oloompa !

Naming rules of what? 
If you're talking about **commit**, there is [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/)

Best

**Comment by Oloompa** [comment]
I was thinking about file names

**Comment by RemyTinco** [comment]
Oh, I don't think there is a standard for File/Folder naming as popular as conventional commit.

I think it depends on your architecture, but it's best to use what you're comfortable with.
